### ISSUE TITLE
1 % training of ReDAL

### ISSUE THREAD

**Issue by WEIJIARONG99** [hzykent/LiDAL#2]
Hi:
First thank you very much for your wonderful work!
I have one question, when you retrain ReDAL using SPVCNN, do you have any clue why the initial training at 1% is higher than they reported? (you reached around 48.8 while what they reported is only around 41.9) 
They use 4 Tesla V100 GPUs, set the batch size to 4, and trained it for 100 epochs;
Did you use a different setting to reproduce their work? For me I use the same configuration as theirs and I got similar results, around 42 - 44% for first 1%.

**Comment by hzykent** [comment]
Hi, thank you for your interest.

As mentioned in the paper, in the initial round, we train the network for 20000 iterations instead of 100 epochs to ensure the convergence. I'll say the performance gap may come from the difference on whether the network achieves convergence.

Cheers~
Zeyu

On 15 Jan 2023, at 7:00 PM, Tony-WJR ***@***.***> wrote:

﻿

Hi:
First thank you very much for your wonderful work!
I have one question, when you retrain ReDAL using SPVCNN, do you have any clue why the initial training at 1% is higher than they reported? (you reached around 48.8 while what they reported is only around 41.9)
They use 4 Tesla V100 GPUs, set the batch size to 4, and trained it for 100 epochs;
Did you use a different setting to reproduce their work? For me I use the same configuration as theirs and I got similar results, around 42 - 44% for first 1%.

**Comment by WEIJIARONG99** [comment]
This answers my question. Thank you so much for your reply!
